/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Block dropdown search",
  "description": "Allows you to search the options in block dropdowns.",
  "credits": [
    {
      "name": "GarboMuffin"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userscript.css"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": true
};
//glow-start  not reliable enough  https://github.com/glow-ets/scratch-gui/issues/16
//import {isMobile} from "../../environment";
//if (isMobile) manifest.enabledByDefault = false;
//glow-end

export default manifest;
