/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Glow Lab: Disable webcam",
  "description": "Stop every extension from using the webcam, and hide Video Sensing, Face Sensing and Glow ML Webcam from the extension list. Projects that use them still open; their blocks say the webcam is not allowed. Also turned on by the dgw URL parameter. This is a guard for the classroom, not a lock: to really forbid the camera, block it with a browser policy.",
  "credits": [
    {
      "name": "Glow ETS",
      "link": "https://glow.earth"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "danger"
  ],
  "enabledByDefault": false,
  "dynamicEnable": true,
  "dynamicDisable": true
};
export default manifest;
