/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Glow Lab branding",
  "description": "Glow Lab logo, version badge, and pink menu bar.",
  "credits": [
    {
      "name": "Glow Lab",
      "link": "https://glow.earth"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": true,
  "glowAdvanced": true,
  "dynamicEnable": true,
  "dynamicDisable": true
};
export default manifest;
