/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _asset from "!url-loader!./glow-lab-small.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "glow-lab-small.svg": _asset,
};
